### ISSUE TITLE
Formatting not gofmt compliant

### ISSUE THREAD

**Issue by catay** [torbiak/gopl#3]
Hi,

I also noticed the examples are not gofmt compliant. 
Maybe this was intentionally,  if not, let me know and I can submit a PR.

$ gofmt -l . |head -10
ex1.12/main.go
ex1.3/concat_test.go
ex1.4/main.go
ex1.5/main.go
ex1.6/main.go
ex1.7/main.go
ex1.8/main.go
ex1.9/main.go
ex10.1/imgconv.go
ex10.2/arprint.go
...

Cheers,

Steven

**Comment by torbiak** [comment]
Sure, if you submit a PR for it I'll merge it.
